apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: task-manager
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: taskdb
